# Stage 1 - the build process
FROM node:14 as build
WORKDIR /app
COPY package*.json ./
RUN yarn
COPY . /app
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]